services:
  rails: &services-rails
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/opt/app

# TODO: figure out whether we need an updater service, & if not, how to precompile assets

#  updater:
#    <<: *services-rails
#    command:
#      - assets:precompile
#    ports: []
#    restart: "no"

version: "3.7"
