version: "3.8"

services:
  app:
    build: .
    environment:
      - LIT_SHOW_HOMEPAGE=1
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=foobar
    ports:
      - 3000:3000
    restart: always
    volumes:
      # Note that this mounts the *entire* repo directory (including
      # files ignored in .dockerignore when building the image)
      - ./:/opt/app
