services:
  rails: &services-rails
    build:
      context: .
      target: development
    ports:
      - target: 3000
        published: 3000
    restart: always
    volumes:
      # Note that this mounts the *entire* repo directory (including
      # files ignored in .dockerignore when building the image)
      - ./:/opt/app

# TODO: figure out whether we need an updater service, & if not, how to precompile assets

#  updater:
#    <<: *services-rails
#    command:
#      - assets:precompile
#    ports: []
#    restart: "no"

version: "3.7"
