name: Test Docker image

on:
  workflow_call:
    inputs:
      image:
        type: string

env:
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  DOCKER_APP_IMAGE: ${{ inputs.image }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the test script
        run: |
          docker compose run --rm --user root app chown -R avplayer:avplayer artifacts
          docker compose up --detach --wait
          docker compose exec app bin/test
